name: rtl_433
version: "0.1.0"
slug: rtl433
description: "Receive wireless sensor data via an SDR dongle and rtl_433"
url: https://github.com/stuartparmenter/rtl433-addon
arch: [armhf, armv7, aarch64, amd64, i386]
image: "ghcr.io/stuartparmenter/{arch}-rtl433-addon"
init: false
map: [addon_config:rw]
services: [mqtt:want]
usb: true
udev: true
options:
  rtl_433_conf_file: ""
  retain: true
schema:
  rtl_433_conf_file: str?
  retain: bool