name: CI

env:
  MONITORED_FILES: "build.yaml config.yaml Dockerfile run.sh rtl_433.conf.template"
  ARCHITECTURES: '["amd64", "aarch64"]'
  IMAGE_NAME: rtl433-addon

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    permissions:
      contents: read
    outputs:
      changed: ${{ steps.changed_addons.outputs.changed }}
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6

      - name: Check if add-on files changed
        id: changed_addons
        run: |
          for file in ${{ env.MONITORED_FILES }}; do
            if [[ "${{ steps.changed_files.outputs.all_changed_files }}" =~ $file ]]; then
              echo "Add-on files changed, triggering build";
              echo "changed=true" >> $GITHUB_OUTPUT;
              exit 0
            fi
          done
          echo "No monitored files changed (${{ env.MONITORED_FILES }})";
          echo "changed=false" >> $GITHUB_OUTPUT;

      - name: Get build matrix
        if: steps.changed_addons.outputs.changed == 'true'
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@62a1597b84b3461abad9816d9cd92862a2b542c3 # 2026.03.2
        with:
          architectures: ${{ env.ARCHITECTURES }}
          image-name: ${{ env.IMAGE_NAME }}

  build:
    needs: init
    if: needs.init.outputs.changed == 'true'
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.arch }} add-on
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Get build configuration
        id: config
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          echo "build_from=$(yq ".build_from.${ARCH}" build.yaml)" >> $GITHUB_OUTPUT
          echo "librtlsdr_git_revision=$(yq '.args.librtlsdrGitRevision' build.yaml)" >> $GITHUB_OUTPUT
          echo "rtl433_git_revision=$(yq '.args.rtl433GitRevision' build.yaml)" >> $GITHUB_OUTPUT

      - name: Build add-on
        uses: home-assistant/builder/actions/build-image@62a1597b84b3461abad9816d9cd92862a2b542c3 # 2026.03.2
        with:
          arch: ${{ matrix.arch }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          cosign: "false"
          image: ${{ matrix.image }}
          image-tags: test
          push: "false"
          version: test
          build-args: |
            BUILD_FROM=${{ steps.config.outputs.build_from }}
            librtlsdrGitRevision=${{ steps.config.outputs.librtlsdr_git_revision }}
            rtl433GitRevision=${{ steps.config.outputs.rtl433_git_revision }}
